# Site settings
title: Nate Berkopec
email: nate.berkopec@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of Nate Berkopec, Ruby on Rails programmer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nateberkopec.com" # the base hostname & protocol for your site
author: Nate Berkopec
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
future:      false
unpublished: false

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master

gems:
  - jekyll-assets
  - bootstrap-sass

assets:
  js_compressor:  uglifier
  css_compressor: sass
  prefix: "/assets"
  assets:
    - "*.png"
    - "base.css"
  digest: true
  sources:
    - "assets"
    - "assets/css"
    - "assets/img"
    - "_sass"

